// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: pkg/logshipper/proto/logshipper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry represents a single log line with metadata.
type LogEntry struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PodName      string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	// component identifies the upgrade component (e.g., cluster-upgrade, node-upgrade, image-preload).
	Component         string `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Node              string `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	Line              []byte `protobuf:"bytes,5,opt,name=line,proto3" json:"line,omitempty"`
	TimestampUnixNano int64  `protobuf:"varint,6,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkg_logshipper_proto_logshipper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_logshipper_proto_logshipper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_logshipper_proto_logshipper_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *LogEntry) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *LogEntry) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *LogEntry) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *LogEntry) GetLine() []byte {
	if x != nil {
		return x.Line
	}
	return nil
}

func (x *LogEntry) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

// StreamLogsResponse is returned when the client-side stream ends.
type StreamLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BytesReceived int64                  `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_pkg_logshipper_proto_logshipper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_logshipper_proto_logshipper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_logshipper_proto_logshipper_proto_rawDescGZIP(), []int{1}
}

func (x *StreamLogsResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

var File_pkg_logshipper_proto_logshipper_proto protoreflect.FileDescriptor

const file_pkg_logshipper_proto_logshipper_proto_rawDesc = "" +
	"\n" +
	"%pkg/logshipper/proto/logshipper.proto\x12\n" +
	"logshipper\"\xc0\x01\n" +
	"\bLogEntry\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x12\n" +
	"\x04node\x18\x04 \x01(\tR\x04node\x12\x12\n" +
	"\x04line\x18\x05 \x01(\fR\x04line\x12.\n" +
	"\x13timestamp_unix_nano\x18\x06 \x01(\x03R\x11timestampUnixNano\";\n" +
	"\x12StreamLogsResponse\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x03R\rbytesReceived2T\n" +
	"\fLogCollector\x12D\n" +
	"\n" +
	"StreamLogs\x12\x14.logshipper.LogEntry\x1a\x1e.logshipper.StreamLogsResponse(\x01B;Z9github.com/harvester/upgrade-toolkit/pkg/logshipper/protob\x06proto3"

var (
	file_pkg_logshipper_proto_logshipper_proto_rawDescOnce sync.Once
	file_pkg_logshipper_proto_logshipper_proto_rawDescData []byte
)

func file_pkg_logshipper_proto_logshipper_proto_rawDescGZIP() []byte {
	file_pkg_logshipper_proto_logshipper_proto_rawDescOnce.Do(func() {
		file_pkg_logshipper_proto_logshipper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_logshipper_proto_logshipper_proto_rawDesc), len(file_pkg_logshipper_proto_logshipper_proto_rawDesc)))
	})
	return file_pkg_logshipper_proto_logshipper_proto_rawDescData
}

var file_pkg_logshipper_proto_logshipper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_logshipper_proto_logshipper_proto_goTypes = []any{
	(*LogEntry)(nil),           // 0: logshipper.LogEntry
	(*StreamLogsResponse)(nil), // 1: logshipper.StreamLogsResponse
}
var file_pkg_logshipper_proto_logshipper_proto_depIdxs = []int32{
	0, // 0: logshipper.LogCollector.StreamLogs:input_type -> logshipper.LogEntry
	1, // 1: logshipper.LogCollector.StreamLogs:output_type -> logshipper.StreamLogsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_logshipper_proto_logshipper_proto_init() }
func file_pkg_logshipper_proto_logshipper_proto_init() {
	if File_pkg_logshipper_proto_logshipper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_logshipper_proto_logshipper_proto_rawDesc), len(file_pkg_logshipper_proto_logshipper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_logshipper_proto_logshipper_proto_goTypes,
		DependencyIndexes: file_pkg_logshipper_proto_logshipper_proto_depIdxs,
		MessageInfos:      file_pkg_logshipper_proto_logshipper_proto_msgTypes,
	}.Build()
	File_pkg_logshipper_proto_logshipper_proto = out.File
	file_pkg_logshipper_proto_logshipper_proto_goTypes = nil
	file_pkg_logshipper_proto_logshipper_proto_depIdxs = nil
}
