name: Pull Request Build

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.8.0

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run tests
        run: |
          go mod tidy && git diff --exit-code go.mod go.sum
          make test

  build:
    name: Build binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: make build

  build-image:
    name: Build image
    uses: ./.github/workflows/build-image.yml
    permissions:
      contents: read
      id-token: write
    with:
      push: false
      tags: rancher/harvester-upgrade-toolkit:ci-${{ github.event.pull_request.number }}
      version: ci-${{ github.event.pull_request.number }}
      git_commit: ${{ github.sha }}
